### PR TITLE
parse solution for projects. fixed some issues

### PR DESCRIPTION
**Pull request by pavelliavonau**
Hello. Please Consider my changes to merge. I done '-s' option for solution path to convert whole solution itself. Also made a proper list of source files and dependencies of targets after solution pass.

### CODE REVIEW

**Comment by algorys** [comment]
Thanks and very nice PR @pavelliavonau :wink: .

Do you have a solution that you have tested on ?

**Comment by pavelliavonau** [comment]
I used visual studio for developing. Do you mean sln file with Python project?
I haven't tested it with your tests because it was rapid development). And I have no so much time. Also I have more local changes that improve converter. Can you help me with tests? I have no experience of using them)

**Comment by algorys** [comment]
No I mean a visual test solution to test your modifications.

For checks, you must:

* Pass `pycodestyle` and `pylint` (for Python code style), so function should be lowercase, no space trailing, ...
* Unit Tests fails because, in your changes, you parse each `.vcxproj` file inside project and they are no presents in repository. (like in `test_files` folder). And some other things seems broken...

I'll try to have a look.

**Comment by algorys** [comment]
I've fix Unit Tests and PEP8/Pylint codestyle.

Now I make tests on my side.

**Comment by pavelliavonau** [comment]
I've pulled your changes amd merged them with my local repo. It seems that everything is Ok.
Thank you.
I'll use PEP8 from this moment and try to commit some additional patches without hardcode hacks.

**Comment by algorys** [comment]
@pavelliavonau Ok. Normally, problems are solved. 

Missing only case, if any `.vcxproj` are in the same folder, the script will overwrite the `CMakeLists.txt` as you go along.

So I'm looking for a solution that would prevent that. Maybe by create a dedicated folder for each CMakeLists.txt ?

**Comment by pavelliavonau** [comment]
> So I'm looking for a solution that would prevent that. Maybe by create a dedicated variables for each project reference ?
yes, maybe. But it's bad practice to hold many vcxproj files at the same directory I guess.
It's not major problem.  Look at my commit. I removed hard code of configurations. Help me, please with project variables. Let's make it beautiful!)

**Comment by algorys** [comment]
@pavelliavonau I'll merge this PR after I clean the Unit Tests.

So please push other changes to a new PR :wink:

**Comment by pavelliavonau** [comment]
write_dependencies2 fixes order of building of many targets. 
With variables... I guess you saw the Todo item. I just want to remove hard code of 4 configurations only.
About your references management I not sure that we must create additional cmake file. Look at my mensioned function). Also name of target should be got at the same way(root namespace. Not filename).

**Comment by algorys** [comment]
Ok for `write_dependencies2`.

Yes I've seen your TODO. You can make another PR for that if you had the time.

You can test develop version to see what I've done for CMake files.

**Comment by algorys** [comment]
@pavelliavonau I've push a new release and review problem you said.

Tell me if you want to talk about some things :wink:

**Pull request merged**
